name: run tests#1187

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
   

    steps:
      - uses: actions/checkout@v4
        

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: 'arm64'
          
     
