name: Debug

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          env
          python -m pip install --upgrade pip pip-tools
          CPUCOUNT=1 pip install python-snappy==0.6.1
